#include <iostream>
#include <string>
#include <exception>
using namespace std;

int main() {
    string S;
    cin >> S;
    
    try {
        int number = stoi(S);
        cout << number << endl;
    } catch (invalid_argument const &e) {
        cout << "Bad String" << endl;
    } catch (out_of_range const &e) {
        cout << "Bad String" << endl;
    }
    
    return 0;
}
